resolver: lts-11.2
packages:
- .
- subs/rio

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- Cabal-2.2.0.1@rev:0
- hackage-security-0.5.3.0@rev:0
- hpack-0.28.2
- http-api-data-0.3.8.1@rev:0
